//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNHAP
    {
        public string MATAIKHOAN { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<decimal> QUYENTRUYCAP { get; set; }
        public int SOLANDN { get; set; }
        public int DOIMATKHAU { get; set; }
        public string MATKHAUBANDAU { get; set; }
    }
}
