//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMDOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOMDOCGIA()
        {
            this.THONGTINDOCGIAs = new HashSet<THONGTINDOCGIA>();
        }
    
        public string MANHOM { get; set; }
        public string MAQUYDINH { get; set; }
        public string TENNHOM { get; set; }
    
        public virtual QUYDINH QUYDINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINDOCGIA> THONGTINDOCGIAs { get; set; }
    }
}
