//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUONTRA
    {
        public string MAPHIEU { get; set; }
        public string MADOCGIA { get; set; }
        public string MANHANVIEN { get; set; }
        public Nullable<System.DateTime> NGAYMUON { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<decimal> TIENPHAT { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THONGTINDOCGIA THONGTINDOCGIA { get; set; }
    }
}
