//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTHUVIENEntities : DbContext
    {
        public QUANLYTHUVIENEntities()
            : base("name=QUANLYTHUVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOPHAN> BOPHANs { get; set; }
        public virtual DbSet<DANGNHAP> DANGNHAPs { get; set; }
        public virtual DbSet<GOPYDOCGIA> GOPYDOCGIAs { get; set; }
        public virtual DbSet<NGONNGU> NGONNGUs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHOMDOCGIA> NHOMDOCGIAs { get; set; }
        public virtual DbSet<PHIEUMUONTRA> PHIEUMUONTRAs { get; set; }
        public virtual DbSet<QUYDINH> QUYDINHs { get; set; }
        public virtual DbSet<THONGTINCUONSACH> THONGTINCUONSACHes { get; set; }
        public virtual DbSet<THONGTINDAUSACH> THONGTINDAUSACHes { get; set; }
        public virtual DbSet<THONGTINDOCGIA> THONGTINDOCGIAs { get; set; }
        public virtual DbSet<THONGTINKESACH> THONGTINKESACHes { get; set; }
        public virtual DbSet<THONGTINLOAISACH> THONGTINLOAISACHes { get; set; }
        public virtual DbSet<THONGTINNHAXUATBAN> THONGTINNHAXUATBANs { get; set; }
        public virtual DbSet<THONGTINNOPPHI> THONGTINNOPPHIs { get; set; }
        public virtual DbSet<THONGTINSACHMUON> THONGTINSACHMUONs { get; set; }
        public virtual DbSet<THONGTINTACGIA> THONGTINTACGIAs { get; set; }
    }
}
