//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUYDINH()
        {
            this.NHOMDOCGIAs = new HashSet<NHOMDOCGIA>();
        }
    
        public string MAQUYDINH { get; set; }
        public Nullable<decimal> SONGAYMUONTOIDA { get; set; }
        public Nullable<decimal> SOSACHMUONTOIDA { get; set; }
        public Nullable<decimal> SOTIENPHATTREMOTNGAY { get; set; }
        public Nullable<decimal> SOTIENPHATLAMHUSACH { get; set; }
        public Nullable<decimal> SOTIENPHATLAMMATSACH { get; set; }
        public Nullable<decimal> LEPHICAPTHE { get; set; }
        public Nullable<decimal> LEPHIGIAHAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHOMDOCGIA> NHOMDOCGIAs { get; set; }
    }
}
