//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINDOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINDOCGIA()
        {
            this.PHIEUMUONTRAs = new HashSet<PHIEUMUONTRA>();
        }
    
        public string MADOCGIA { get; set; }
        public string MANHOM { get; set; }
        public string TENDOCGIA { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string TRINHDOHOCVAN { get; set; }
        public Nullable<decimal> SOCMND { get; set; }
        public string NGHENGHIEP { get; set; }
        public string NOICONGTAC { get; set; }
        public string SODIENTHOAIDOCGIA { get; set; }
        public string DIACHIDOCGIA { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public Nullable<int> TRANGTHAIDOCGIA { get; set; }
        public string MATAIKHOAN { get; set; }
        public string HINHANH { get; set; }
    
        public virtual NHOMDOCGIA NHOMDOCGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONTRA> PHIEUMUONTRAs { get; set; }
    }
}
