//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINNOPPHI
    {
        public string MAPHINOP { get; set; }
        public string MADOCGIA { get; set; }
        public Nullable<decimal> PHIDINHKY { get; set; }
        public Nullable<decimal> PHICAPTHE { get; set; }
        public Nullable<decimal> PHATNOPTRE { get; set; }
        public Nullable<decimal> PHATHUSACH { get; set; }
        public Nullable<decimal> PHATMATSACH { get; set; }
        public Nullable<System.DateTime> NGAYNOP { get; set; }
    }
}
