//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINNHAXUATBAN
    {
        public string MANHAXUATBAN { get; set; }
        public string TENNHAXUATBAN { get; set; }
        public string DIACHINHAXUATBAN { get; set; }
    }
}
