//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LY_THU_VIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINDAUSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINDAUSACH()
        {
            this.THONGTINCUONSACHes = new HashSet<THONGTINCUONSACH>();
        }
    
        public string MADAUSACH { get; set; }
        public string MANGONNGU { get; set; }
        public string MANHAXUATBAN { get; set; }
        public string MALOAIDDC { get; set; }
        public string MATACGIA { get; set; }
        public string MAKE { get; set; }
        public string TENDAUSACH { get; set; }
        public string NAMXUATBAN { get; set; }
        public Nullable<decimal> SOTRANG { get; set; }
        public string MAISBN { get; set; }
        public Nullable<decimal> GIABIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINCUONSACH> THONGTINCUONSACHes { get; set; }
    }
}
